apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - jaeger.yaml
  - openobserve.yaml
  - otel-collector.yaml
  - prometheus.yaml
  - api.yaml

configMapGenerator:
  - name: otel-collector-config
    files:
      - config/otel-collector-config.yaml
  - name: prometheus-config
    files:
      - config/prometheus.yml

generatorOptions:
  disableNameSuffixHash: true
